apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: target-resolver
  namespace: cadc
  labels:
    k8s-app: target-resolver
spec:
  replicas: 4
  template:    
    metadata:
      labels:
        name: cadc-target-resolver
    spec:
      containers:
      - name: cadc-target-resolver
        image: opencadc/cadc-target-resolver
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
