apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: target-resolver
  namespace: cadc
  labels:
    k8s-app: target-resolver
spec:
  replicas: 4
  template:    
    metadata:
      labels:
        name: cadc-target-resolver
        k8s-app: target-resolver
    spec:
      containers:
      - name: cadc-target-resolver
        image: opencadc/cadc-target-resolver
        ports:
          - containerPort: 8080